project_name: "sarabi"
version: 2

release:
  github:
    owner: adxgun
    name: sarabi

builds:
  - id: server
    dir: ./cmd
    main: ./main.go
    binary: sarabi-server
    cgo: true
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: cli
    dir: ./client
    main: ./internal/cmd/main.go
    binary: sarabi
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - server
      - cli
