applicationID: 49a6b873-a80a-42e3-a96a-c10e53c377b7
frontend: ""
backend: /Users/lekanadigun/github/adigunhammedolalekan/fspasssample
domain: rtester.app
storageengines:
    - postgres
    - mysql
    - redis
